// Builds the test plan as an .xlsx laid out the way field verification workbooks
// are: a title sheet, a version sheet, one sheet per phase with a stats header
// block driven by live formulas, and a summary that rolls the phases up.
//
// The layout convention is deliberate — anyone who has filled in a vendor
// verification workbook can pick this up cold. Only the shape is shared; every
// word of test content is our own (see test-plan.ts).
//
// The percentage block is FORMULAS, not baked numbers, so when the customer edits
// a Status cell in Excel the counts re-roll themselves. That is the main thing a
// real workbook buys over the CSV.

import { includedEpicList, typeLabel, type Selection } from './deployment-plan';
import {
  buildXlsx,
  colName,
  safeSheetName,
  DXF,
  STYLE,
  type Row,
  type SheetSpec,
} from './xlsx';
import { caseKey, selectedPhases, type TestResults } from './test-plan';

/** Case rows start here; everything above is the header block. */
const DATA_START = 15;

const COLS = [11, 42, 78, 52, 30, 9, 12, 40];
const HEADERS = [
  'ID',
  'Test Description',
  'Action / Input',
  'Expected Results',
  'Actual Results',
  'Status',
  'Date',
  'Notes',
];
const LAST_COL = colName(HEADERS.length - 1); // 'H'
const STATUS_COL = colName(5); // 'F'

/**
 * Steps carry `backticks` and **bold** for the web page. Excel has no inline
 * markup here, so strip the markers and keep the text.
 */
function plain(s: string): string {
  return s.replace(/`([^`]+)`/g, '$1').replace(/\*\*([^*]+)\*\*/g, '$1');
}

function titleSheet(sel: Selection, preparedOn: string): SheetSpec {
  const rows: Row[] = [];
  const put = (r: number, cells: Row) => {
    rows[r - 1] = cells;
  };

  put(1, [{ v: 'VMware Cloud Foundation 9.1', s: STYLE.TITLE }]);
  put(3, [{ v: 'Verification Test Plan', s: STYLE.TITLE }]);
  put(5, [
    { v: 'Scope', s: STYLE.LABEL },
    { v: typeLabel(sel), s: STYLE.VALUE },
  ]);
  put(6, [
    { v: 'Deployment plan epics', s: STYLE.LABEL },
    { v: includedEpicList(sel), s: STYLE.VALUE },
  ]);
  put(7, [
    { v: 'Product version', s: STYLE.LABEL },
    { v: '9.1.x', s: STYLE.VALUE },
  ]);
  put(8, [
    { v: 'Prepared', s: STYLE.LABEL },
    { v: preparedOn, s: STYLE.VALUE },
  ]);

  put(11, [{ v: 'How to use this workbook', s: STYLE.LABEL }]);
  put(12, [
    null,
    {
      v: 'One sheet per test phase, in execution order. Work a phase at a time and do not start the next while the current one still has an open F1.',
      s: STYLE.SUBTITLE,
    },
  ]);
  put(13, [
    null,
    {
      v: 'Set Status from the dropdown: P = pass, F1 = critical failure (blocks the phase gate and handover), F2 = non-critical failure (proceed with a named owner and a date), NA = not applicable.',
      s: STYLE.SUBTITLE,
    },
  ]);
  put(14, [
    null,
    {
      v: 'Always fill Actual Results: the measured value or evidence reference for a pass, the owner and date for an F2, the reason for an NA. A Status with an empty Actual Results is not a pass.',
      s: STYLE.SUBTITLE,
    },
  ]);
  put(15, [
    null,
    {
      v: 'The percentage block at the top of each sheet is live — it recalculates as you fill the Status column in.',
      s: STYLE.SUBTITLE,
    },
  ]);

  put(18, [{ v: 'Generated by the VCF 9.1 Deployment Planning test-plan tool', s: STYLE.SUBTITLE }]);
  put(19, [{ v: 'https://vcf-planning.hollebollevsan.nl/tools/test-plan/', s: STYLE.SUBTITLE }]);

  return {
    name: 'Title',
    rows,
    cols: [26, 110],
    merges: ['A1:B1', 'A3:B3'],
    rowHeights: { 1: 30, 3: 26, 12: 30, 13: 30, 14: 30 },
  };
}

function versionSheet(preparedOn: string): SheetSpec {
  const rows: Row[] = [
    [{ v: 'Version History', s: STYLE.TITLE }],
    [],
    [
      { v: 'Date', s: STYLE.HEADER },
      { v: 'Version', s: STYLE.HEADER },
      { v: 'Author', s: STYLE.HEADER },
      { v: 'Description', s: STYLE.HEADER },
      { v: 'Reviewers', s: STYLE.HEADER },
    ],
    [
      { v: preparedOn, s: STYLE.BODY_CENTER },
      { v: '1.0', s: STYLE.BODY_CENTER },
      { v: '', s: STYLE.BODY },
      { v: 'Initial issue', s: STYLE.BODY },
      { v: '', s: STYLE.BODY },
    ],
    ...Array.from({ length: 8 }, () => [
      { v: '', s: STYLE.BODY_CENTER },
      { v: '', s: STYLE.BODY_CENTER },
      { v: '', s: STYLE.BODY },
      { v: '', s: STYLE.BODY },
      { v: '', s: STYLE.BODY },
    ]),
    [],
    [{ v: 'Use this table to track releases of the workbook to the customer.', s: STYLE.SUBTITLE }],
  ];
  return { name: 'Version', rows, cols: [14, 10, 26, 60, 26], merges: ['A1:E1'], rowHeights: { 1: 26 } };
}

/** The stats block — all formulas, so the customer's edits re-roll it. */
function headerBlock(
  phaseTitle: string,
  epics: string,
  gate: string,
  scope: string,
  lastRow: number,
): Row[] {
  const rng = `${STATUS_COL}${DATA_START}:${STATUS_COL}${lastRow}`;
  // Column A also holds the section band rows, so COUNTA over it over-counts.
  // Case ids are all "TP-nnn", which distinguishes them from a band label.
  const total = `COUNTIF(A${DATA_START}:A${lastRow},"TP-*")`;
  const done = `COUNTIF(${rng},"P")+COUNTIF(${rng},"F1")+COUNTIF(${rng},"F2")+COUNTIF(${rng},"NA")`;
  const pct = (expr: string) => `IFERROR(${expr},0)`;

  const rows: Row[] = [];
  const put = (r: number, cells: Row) => {
    rows[r - 1] = cells;
  };

  put(1, [{ v: `VMware Cloud Foundation 9.1  ·  ${phaseTitle}`, s: STYLE.TITLE }]);
  put(2, [
    { v: 'Architecture Model', s: STYLE.LABEL },
    { v: scope, s: STYLE.VALUE },
    null,
    { v: 'Product Version', s: STYLE.LABEL },
    { v: '9.1.x', s: STYLE.VALUE },
  ]);
  put(3, [
    { v: 'Covers', s: STYLE.LABEL },
    { v: epics, s: STYLE.VALUE },
    null,
    { v: 'Total Test Cases', s: STYLE.LABEL },
    { f: total, s: STYLE.COUNT },
  ]);
  put(4, [
    { v: 'Gate', s: STYLE.LABEL },
    { v: gate, s: STYLE.SUBTITLE },
  ]);

  put(6, [
    { v: 'Completed Test Cases', s: STYLE.LABEL },
    { f: done, s: STYLE.COUNT },
  ]);
  put(7, [
    { v: '% Actioned Cases', s: STYLE.LABEL },
    { f: pct(`(${done})/(${total})`), s: STYLE.PERCENT },
  ]);
  put(8, [
    { v: '% Remaining Cases', s: STYLE.LABEL },
    { f: pct(`1-(${done})/(${total})`), s: STYLE.PERCENT },
  ]);
  put(9, [
    { v: '% Passing Cases (Actioned)', s: STYLE.LABEL },
    { f: pct(`COUNTIF(${rng},"P")/(${done})`), s: STYLE.PERCENT },
  ]);
  put(10, [
    { v: '% Critical Failure (Actioned)', s: STYLE.LABEL },
    { f: pct(`COUNTIF(${rng},"F1")/(${done})`), s: STYLE.PERCENT },
  ]);
  put(11, [
    { v: '% Non-Critical Failure (Actioned)', s: STYLE.LABEL },
    { f: pct(`COUNTIF(${rng},"F2")/(${done})`), s: STYLE.PERCENT },
  ]);
  put(12, [
    { v: '% N/A Cases (Actioned)', s: STYLE.LABEL },
    { f: pct(`COUNTIF(${rng},"NA")/(${done})`), s: STYLE.PERCENT },
  ]);

  put(14, HEADERS.map((h) => ({ v: h, s: STYLE.HEADER })));
  return rows;
}

export async function buildTestPlanWorkbook(
  sel: Selection,
  results: TestResults = {},
  preparedOn = '',
): Promise<Blob> {
  const phases = selectedPhases(sel);
  const scope = typeLabel(sel);
  const taken = new Set<string>();
  const sheets: SheetSpec[] = [titleSheet(sel, preparedOn), versionSheet(preparedOn)];
  // Reserve the names so a phase called "Summary" cannot collide.
  taken.add('title');
  taken.add('version');
  taken.add('summary');

  for (const p of phases) {
    const body: Row[] = [];
    let lastSection = '';

    for (const c of p.cases) {
      // Band rows group the sheet the way a verification workbook does.
      const section = `${c.epic} — Story ${c.story}`;
      if (section !== lastSection) {
        lastSection = section;
        body.push([{ v: section, s: STYLE.SECTION }, ...Array(HEADERS.length - 1).fill({ v: '', s: STYLE.SECTION })]);
      }
      const r = results[caseKey(p, c)];
      body.push([
        { v: c.id, s: STYLE.MONO },
        { v: plain(c.title) + (c.critical ? '  [CRITICAL]' : '') + (c.automatable ? '  [AUTO]' : ''), s: STYLE.BODY },
        { v: c.steps.map((s, i) => `${i + 1}. ${plain(s)}`).join('\n'), s: STYLE.BODY },
        { v: plain(c.expected), s: STYLE.BODY },
        { v: r?.actual ?? '', s: STYLE.BODY },
        { v: r?.status ?? '', s: STYLE.BODY_CENTER },
        { v: r?.date ?? '', s: STYLE.BODY_CENTER },
        { v: c.note ? plain(c.note) : '', s: STYLE.BODY },
      ]);
    }

    const lastRow = DATA_START + body.length - 1;
    const header = headerBlock(p.title, p.epics, p.gate, scope, lastRow);
    const rows: Row[] = [...header];
    rows.length = DATA_START - 1; // pad out to the data start
    rows.push(...body);

    const statusRange = `${STATUS_COL}${DATA_START}:${STATUS_COL}${lastRow}`;
    sheets.push({
      name: safeSheetName(`${p.id} ${p.title}`, taken),
      rows,
      cols: COLS,
      freezeAtRow: DATA_START,
      autoFilter: `A${DATA_START - 1}:${LAST_COL}${lastRow}`,
      merges: ['A1:H1', `B4:${LAST_COL}4`],
      rowHeights: { 1: 26, 4: 28, [DATA_START - 1]: 26 },
      validations: [{ sqref: statusRange, values: ['P', 'F1', 'F2', 'NA'] }],
      conditionalFormats: [
        { sqref: statusRange, equals: 'P', dxf: DXF.PASS },
        { sqref: statusRange, equals: 'F1', dxf: DXF.FAIL_CRITICAL },
        { sqref: statusRange, equals: 'F2', dxf: DXF.FAIL_MINOR },
        { sqref: statusRange, equals: 'NA', dxf: DXF.NA },
      ],
    });
  }

  // --- Summary --------------------------------------------------------------
  // Cross-sheet formulas so the roll-up follows the customer's own edits too.
  const summaryRows: Row[] = [
    [{ v: 'VMware Cloud Foundation 9.1  ·  Verification Summary', s: STYLE.TITLE }],
    [],
    [
      { v: 'Scope', s: STYLE.LABEL },
      { v: scope, s: STYLE.VALUE },
    ],
    [
      { v: 'Prepared', s: STYLE.LABEL },
      { v: preparedOn, s: STYLE.VALUE },
    ],
    [],
    [
      { v: 'Phase', s: STYLE.HEADER },
      { v: 'Covers', s: STYLE.HEADER },
      { v: 'Cases', s: STYLE.HEADER },
      { v: 'Actioned', s: STYLE.HEADER },
      { v: 'Pass', s: STYLE.HEADER },
      { v: 'F1', s: STYLE.HEADER },
      { v: 'F2', s: STYLE.HEADER },
      { v: 'N/A', s: STYLE.HEADER },
    ],
  ];

  const firstPhaseRow = summaryRows.length + 1;
  phases.forEach((p, i) => {
    const sheetRef = `'${sheets[i + 2].name}'`;
    const rng = `${sheetRef}!${STATUS_COL}:${STATUS_COL}`;
    summaryRows.push([
      { v: `${p.id} — ${p.title}`, s: STYLE.BODY },
      { v: p.epics, s: STYLE.BODY_CENTER },
      { v: p.cases.length, num: true, s: STYLE.BODY_CENTER },
      { f: `COUNTIF(${rng},"P")+COUNTIF(${rng},"F1")+COUNTIF(${rng},"F2")+COUNTIF(${rng},"NA")`, s: STYLE.BODY_CENTER },
      { f: `COUNTIF(${rng},"P")`, s: STYLE.BODY_CENTER },
      { f: `COUNTIF(${rng},"F1")`, s: STYLE.BODY_CENTER },
      { f: `COUNTIF(${rng},"F2")`, s: STYLE.BODY_CENTER },
      { f: `COUNTIF(${rng},"NA")`, s: STYLE.BODY_CENTER },
    ]);
  });

  const lastPhaseRow = summaryRows.length;
  summaryRows.push([
    { v: 'Total', s: STYLE.SECTION },
    { v: '', s: STYLE.SECTION },
    ...['C', 'D', 'E', 'F', 'G', 'H'].map((col) => ({
      f: `SUM(${col}${firstPhaseRow}:${col}${lastPhaseRow})`,
      s: STYLE.SECTION,
    })),
  ]);

  const totalRow = summaryRows.length;
  summaryRows.push([]);
  summaryRows.push([
    { v: 'Verdict', s: STYLE.LABEL },
    {
      f:
        `IF(F${totalRow}>0,"NOT ACCEPTED - "&F${totalRow}&" critical failure(s) open",` +
        `IF(D${totalRow}<C${totalRow},"INCOMPLETE - "&(C${totalRow}-D${totalRow})&" case(s) not executed",` +
        `IF(G${totalRow}>0,"ACCEPTED WITH ACTIONS - "&G${totalRow}&" non-critical failure(s) carried","ACCEPTED")))`,
      s: STYLE.COUNT,
    },
  ]);
  summaryRows.push([]);
  summaryRows.push([
    null,
    {
      v: 'This sheet recalculates from the phase sheets, so it stays correct as the workbook is filled in.',
      s: STYLE.SUBTITLE,
    },
  ]);

  sheets.push({
    name: 'Summary',
    rows: summaryRows,
    cols: [46, 14, 9, 11, 9, 9, 9, 9],
    merges: ['A1:H1'],
    rowHeights: { 1: 26, 6: 24 },
  });

  // Keep the summary second, right after Title — it is the first thing a reader wants.
  const summary = sheets.pop()!;
  sheets.splice(1, 0, summary);

  return buildXlsx(sheets);
}
